/**
 * Regenerate apps/web/src/qr-tables.ts.
 *
 * The block structure of a QR symbol (how many error-correction blocks, how
 * many EC codewords each carries) is tabulated in ISO/IEC 18004, not derivable
 * from a formula. Rather than copy 320 numbers by hand, read them out of the
 * `qrcode` package (MIT, dev dependency, never shipped) and write them into a
 * source file. The encoder itself is ours; these are the standard's numbers.
 *
 *   node tools/qr-tables/extract.mjs
 *
 * The output is committed. Re-run only if you suspect a bad row; the QR tests
 * decode real symbols with an independent decoder and would catch one.
 */
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const ec = require('qrcode/lib/core/error-correction-code.js');
const ecl = require('qrcode/lib/core/error-correction-level.js');
const utils = require('qrcode/lib/core/utils.js');

const levels = { L: ecl.L, M: ecl.M, Q: ecl.Q, H: ecl.H };
const blocks = {};
const ecPer = {};
for (const [name, level] of Object.entries(levels)) {
  blocks[name] = [0];
  ecPer[name] = [0];
  for (let v = 1; v <= 40; v++) {
    const n = ec.getBlocksCount(v, level);
    blocks[name].push(n);
    ecPer[name].push(ec.getTotalCodewordsCount(v, level) / n);
  }
}
const total = [0];
for (let v = 1; v <= 40; v++) total.push(utils.getSymbolTotalCodewords(v));

const row = (a) => a.join(', ');
const out = `export type Level = 'L' | 'M' | 'Q' | 'H';

/**
 * Error-correction block structure per version and level, from ISO/IEC 18004
 * tables 13 to 22: facts about the standard, not choices. Generated by
 * tools/qr-tables/extract.mjs; checked by decoding real symbols in the tests.
 * Index 0 is unused so version numbers read naturally.
 */

/** Total codewords (data + error correction) in a symbol, by version. */
export const TOTAL_CODEWORDS: readonly number[] = [
  ${row(total)},
];

/** Number of error-correction blocks, by level then version. */
export const EC_BLOCKS: Readonly<Record<Level, readonly number[]>> = {
${Object.keys(levels).map((k) => `  ${k}: [${row(blocks[k])}],`).join('\n')}
};

/** Error-correction codewords per block, by level then version. */
export const EC_PER_BLOCK: Readonly<Record<Level, readonly number[]>> = {
${Object.keys(levels).map((k) => `  ${k}: [${row(ecPer[k])}],`).join('\n')}
};
`;
const target = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'apps', 'web', 'src', 'qr-tables.ts');
writeFileSync(target, out);
console.log(`wrote ${target}`);
